#!/bin/bash
cython -a ./activity.pyx
gcc -shared -pthread -fPIC -fwrapv -O2 -Wall -fno-strict-aliasing  \
    -I /usr/lib64/python2.7/site-packages/numpy/core/include/ \
    -I/usr/include/python2.7 -o activity.so ./activity.c
python main.py -i ./_tiff_data/test/
